[2022-05-29 16:06:20,987] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: user_processing.creating_table scheduled__2022-05-28T00:00:00+00:00 [queued]>
[2022-05-29 16:06:20,991] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: user_processing.creating_table scheduled__2022-05-28T00:00:00+00:00 [queued]>
[2022-05-29 16:06:20,991] {taskinstance.py:1357} INFO - 
--------------------------------------------------------------------------------
[2022-05-29 16:06:20,991] {taskinstance.py:1358} INFO - Starting attempt 1 of 1
[2022-05-29 16:06:20,991] {taskinstance.py:1359} INFO - 
--------------------------------------------------------------------------------
[2022-05-29 16:06:21,018] {taskinstance.py:1378} INFO - Executing <Task(SqliteOperator): creating_table> on 2022-05-28 00:00:00+00:00
[2022-05-29 16:06:21,020] {standard_task_runner.py:52} INFO - Started process 106813 to run task
[2022-05-29 16:06:21,024] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'user_processing', 'creating_table', 'scheduled__2022-05-28T00:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp7w5y8i5f', '--error-file', '/tmp/tmpc1dipuo4']
[2022-05-29 16:06:21,024] {standard_task_runner.py:80} INFO - Job 2: Subtask creating_table
[2022-05-29 16:06:21,074] {task_command.py:370} INFO - Running <TaskInstance: user_processing.creating_table scheduled__2022-05-28T00:00:00+00:00 [running]> on host airflowvm
[2022-05-29 16:06:21,193] {taskinstance.py:1570} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=creating_table
AIRFLOW_CTX_EXECUTION_DATE=2022-05-28T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-28T00:00:00+00:00
[2022-05-29 16:06:21,194] {sqlite.py:59} INFO - Executing: 
                CREATE TABLE if not exists users (
                    firstname TEXT NOT NULL,
                    lastname TEXT NOT NULL,
                    country TEXT NOT NULL,
                    username TEXT NOT NULL,
                    password TEXT NOT NULL,
                    email TEXT NOT NULL PRIMARY KEY
                );
            
[2022-05-29 16:06:21,197] {base.py:68} INFO - Using connection ID 'db_sqlite' for task execution.
[2022-05-29 16:06:21,197] {dbapi.py:208} INFO - Running statement: 
                CREATE TABLE if not exists users (
                    firstname TEXT NOT NULL,
                    lastname TEXT NOT NULL,
                    country TEXT NOT NULL,
                    username TEXT NOT NULL,
                    password TEXT NOT NULL,
                    email TEXT NOT NULL PRIMARY KEY
                );
            , parameters: []
[2022-05-29 16:06:21,204] {taskinstance.py:1396} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=creating_table, execution_date=20220528T000000, start_date=20220529T160620, end_date=20220529T160621
[2022-05-29 16:06:21,236] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-05-29 16:06:21,271] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
